### ISSUE TITLE
Add OIDC to view

### ISSUE THREAD

**Issue by InfaNaSotku** [InfaNaSotku/NSUDA#25]
- [x] #28
- [x] #29
- [x] Setting up session with backend
- [x] Send auth code to backend 
- [x] Update view after auth
